language: python
python:
  - "2.7"
install: 
  - "pip install -r requirements.txt"
  - "python -m nltk.downloader book"
script: "echo 'We had neither army nor general ready to impede his march.' | python sentenceMatch.py  | grep 'Match Index: 12000'"
